"""Build a source-wide navigation index without importing DivineOS."""
import argparse
import ast
from collections import Counter
import hashlib
import json
from pathlib import Path


def survey(source: Path):
    source = source.resolve()
    if not (source / "src/divineos").is_dir():
        raise ValueError("Expected src/divineos in --source")
    modules = {}
    imports = Counter()
    for path in sorted((source / "src/divineos").rglob("*.py")):
        raw = path.read_bytes()
        text = raw.decode("utf-8-sig")
        tree = ast.parse(text, filename=str(path))
        name = ".".join(path.relative_to(source / "src").with_suffix("").parts).removesuffix(".__init__")
        references = []
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom) and node.module and node.module.startswith("divineos"):
                references.append(node.module)
            elif isinstance(node, ast.Import):
                references.extend(a.name for a in node.names if a.name.startswith("divineos"))
        imports.update(references)
        modules[name] = {
            "file": path.relative_to(source).as_posix(),
            "lines": len(text.splitlines()),
            "source_description": (ast.get_docstring(tree) or "").split("\n")[0],
            "absolute_local_imports": sorted(set(references)),
            "sha256": hashlib.sha256(raw).hexdigest(),
        }
    return {"modules": modules, "most_imported": imports.most_common(),
            "module_count": len(modules), "physical_lines": sum(m["lines"] for m in modules.values())}


def render(data):
    lines = ["# Source atlas", "", "Generated by `tools/survey_source.py` without importing project code.", "",
             f"{data['module_count']} Python modules; {data['physical_lines']:,} physical lines (including comments and docstrings).", "",
             "Descriptions below are source docstrings, not verified behavior. Imports are explicit absolute imports found by AST; dynamic and relative imports are not resolved. Every source file is hashed in the companion manifest. The archive working tree is the input, not an assumed clean Git commit.", ""]
    last = None
    for _, module in sorted(data["modules"].items(), key=lambda pair: pair[1]["file"]):
        group = str(Path(module["file"]).parent).replace("\\", "/")
        if group != last:
            lines.extend([f"## {group}", ""])
            last = group
        desc = module["source_description"].replace("\r", " ")
        lines.extend([f"### `{Path(module['file']).name}`", "", f"{module['lines']} lines. {desc}", ""])
        if module["absolute_local_imports"]:
            lines.extend(["Imports: " + ", ".join(f"`{x}`" for x in module["absolute_local_imports"]), ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    data = survey(args.source)
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "SOURCE_ATLAS.md").write_text(render(data), encoding="utf-8")
    (args.out / "source-manifest.json").write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps({"modules": data["module_count"], "physical_lines": data["physical_lines"]}))


if __name__ == "__main__":
    main()
